from typing import List, Dict, Tuple


class StrategyConfig:
    """Configuración de trading, indicadores y lógica de mercado."""

    TIMEFRAME = "1h"

    # --- GESTIÓN DE RIESGO ---
    RISK_PER_TRADE_PERCENT = 1.2
    RISK_PER_TRADE = 1.2  # Alias para compatibilidad con reporte
    MAX_RISK_USD = 2.0
    MIN_NOTIONAL_VALUE = 12.0
    MAX_NOTIONAL_MULTIPLIER = 5.0  # Cap de seguridad (Balance * Multiplier)
    MAX_OPEN_TRADES = 1
    MAX_SHADOW_TRADES = 150
    MAX_DIRECTIONAL_TRADES = 3
    LEVERAGE = 10
    IS_DEBUG = False

    TRADE_COOLDOWN_MINUTES = 60
    SHADOW_COOLDOWN_MINUTES = 5
    SYMBOL_COOLDOWN_MINUTES = 30
    SMART_EXIT_COOLDOWN_HOURS = 4
    MAX_TRADE_DURATION_MINUTES = 60

    DAILY_LOSS_LIMIT = 2.0
    DAILY_TRAILING_STOP = 3.0
    DAILY_GOALS = [5.0, 10.0, 15.0]
    DAILY_LOSS_LIMIT_FORCE_PAPER = -3.0

    # --- UMBRALES TÉCNICOS ---
    NATR_THRESHOLD = 2.0
    MIN_VOLUME_24H = 500_000
    MAX_SECTOR_EXPOSURE = 3
    ADX_TREND_THRESHOLD = 20
    MIN_ADX = 15
    MIN_VOL_REL = 0.1

    EMA_9 = 9
    EMA_21 = 21
    EMA_50 = 50
    EMA_200 = 200

    # --- UMBRALES DE CONFIANZA IA ---
    # DELEGADO A core/config/manager.py (Config REAL_MODE_THRESHOLD/SHADOW_MODE_MIN)
    # Se mantiene solo como alias de compatibilidad; la fuente de verdad es manager.py.
    REAL_CONFIDENCE_MIN = 0.70
    SHADOW_PROB_MIN = 0.55
    REAL_CONFIDENCE_THRESHOLD = 0.70

    # --- STOP LOSS Y TAKE PROFIT ---
    ATR_SL_MULTIPLIER_RANGE = 0.2
    ATR_SL_MULTIPLIER_TREND = 1.0
    ATR_TP_MULTIPLIER_RANGE = 1.2
    ATR_TP_MULTIPLIER_TREND = 3.0

    TRAILING_ACTIVATION_PNL = 0.80
    EARLY_BREAKEVEN_ACTIVATION_PNL = 1.5
    TRAILING_BREAKEVEN_PNL = 2.0
    TRAILING_BREAKEVEN_PULLBACK = 1.0  # Subido de 0.8 para dar más aire
    TRAILING_ATR_MULTIPLIER = 2.5

    DYNAMIC_SL_TP = True
    STOP_LOSS_ATR_MODIFIER = 3.0  # Master SL Multiplier
    ATR_SL_MULTIPLIER = 3.0  # Deprecated, use STOP_LOSS_ATR_MODIFIER
    ATR_TP1_MULTIPLIER = 2.0
    ATR_TP2_MULTIPLIER = 4.0

    TP1_ENABLED = True
    TP1_PERCENT = 50
    TP1_LEVEL = 1.8
    TP2_ENABLED = True
    TP2_PERCENT = 50
    TP2_LEVEL = 3.6

    MIN_TP_NET_PERCENT = 0.5
    MIN_TP_SPREAD_MULTIPLIER = 2.0

    # --- FILTROS DE ENTRADA ---
    REAL_RSI_BUY = 30
    REAL_RSI_SELL = 70
    SHADOW_RSI_BUY = 35
    SHADOW_RSI_SELL = 65

    ENTRY_RSI_MIN = 45.0
    ENTRY_RSI_MAX = 68.0
    ENTRY_ADX_MIN = 18.0

    STOCH_REAL_BUY_THRESHOLD = 20
    STOCH_REAL_SELL_THRESHOLD = 70
    STOCH_SHADOW_BUY_THRESHOLD = 30
    STOCH_SHADOW_SELL_THRESHOLD = 70

    # --- BLACKLIST ---
    SYMBOL_BLACKLIST = [
        "PUMP/USDT",
        "KITE/USDT",
        "STABLE/USDT",
        "BERA/USDT",
        "WIF/USDT",
        "ZAMA/USDT",
        "AGLD/USDT",
        "MATIC/USDT",
        "EOS/USDT",
        "FARTCOIN/USDT",
    ]

    # --- ML & PESOS ---
    SMART_AGENT_WEIGHTS = True
    CONTEXTUAL_WEIGHTING = True
    XGB_WEIGHT = 0.30
    LGB_WEIGHT = 0.30
    RF_WEIGHT = 0.20
    GB_WEIGHT = 0.15
    LR_WEIGHT = 0.05

    # --- CRASH PREDICTOR ---
    CRASH_DETECTION_ENABLED = True
    CRASH_PROBABILITY_THRESHOLD = 50
    CRASH_EMERGENCY_THRESHOLD = 70
    CRASH_BTC_DROP_THRESHOLD = 1.5
    CRASH_FUNDING_THRESHOLD = 0.03

    # --- RAG ---
    RAG_ENABLED = True
    RAG_SIMILARITY_THRESHOLD = 0.85
    RAG_MIN_MATCHES = 3

    # --- PARÁMETROS DE PÁNICO Y ESTRATEGIA ADICIONAL ---
    BTC_PANIC_DROP_PERCENT = 1.5
    REAL_HARD_SL_PERCENT = -5.0
    SHADOW_HARD_SL_PERCENT = -10.0
    SHADOW_MIN_PROBABILITY_TREND = 0.65  # [v118]
    SHADOW_MIN_PROBABILITY_RANGE = 0.70  # [v118]
    IA_SHADOW_THRESHOLD = 0.65  # [v118]
    TRAIL_ENTRY_OFFSET = 0.0005
    TRAIL_AFTER_TP = True
    TRAIL_AFTER_TP1 = TRAIL_AFTER_TP
    PRICE_PRIORITY_LIMIT = 0.001
    ML_HEALTH_MIN_ACCURACY = 0.40
    ML_HEALTH_VETO_ENABLED = True
    MAX_MARGIN_PERCENT = 5.0

    # --- PRIORIZACIÓN DE RADAR ---
    RADAR_PRIORITY_HIGH_WR = 1.0
    RADAR_PRIORITY_HIGH_VOL_LOW_PRICE = 0.8
    RADAR_PRIORITY_OTHERS = 0.5
